import type { Metadata } from 'next'
import Container from '@/components/Container'
import Navigation from '@/components/Navigation'
import { ThemeProvider } from '@/components/theme-provider'
import ThemeSwitch from '@/components/ThemeSwitch'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Container>
            <header className="flex items-center justify-between py-6">
              <Navigation />
              <ThemeSwitch />
            </header>
            <main>{children}</main>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  )
}
